server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: local-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: local-logs
          __path__: /var/log/mylogs/*.log
    pipeline_stages:
    - json:
        expressions:
          file_uuid: ""
          level: ""
          msg: ""
    - labels:
        file_uuid:
        level:
